{% set name = "beaupy" %}
{% set version = "3.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/beaupy-{{ version }}.tar.gz
  sha256: bff49ad76d7696c594f86088bca5543ae26de19fb001c77c483f70c9dd303b4b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.2.0
    - python >=3.7.8,<3.12
  run:
    - python >=3.7.8,<3.12
    - rich >=12.2.0
    - emoji >=2.0.0,<3.0.0
    - python-yakh ==0.3.2
    - questo >=0.2.3,<0.3.0

test:
  imports:
    - beaupy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/petereon/beaupy
  doc_url: https://petereon.github.io/beaupy/
  summary: A library of elements for interactive TUIs in Python
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - petereon
    - thewchan
