{% set name = "beaupy" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/beaupy-{{ version }}.tar.gz
  sha256: 54ce1eb477f118bbbb36f79173197c967f9da30d9e427acf6c983f9b7e0348e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0
    - readchar >=3.1.0,<4.0.0
    - rich >=12.5.1,<13.0.0
    - emoji >=2.0.0,<3.0.0

test:
  imports:
    - beaupy

about:
  home: https://github.com/petereon/beaupy
  doc_url: https://petereon.github.io/beaupy/
  summary: A library of elements for interactive TUIs in Python
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
