{% set name = "beaupy" %}
{% set version = "3.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/beaupy-{{ version }}.tar.gz
  sha256: 952ae7191c063756d0a72e7da0fa81127f0b7dda96eca1d154d97a0258a0a83a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.2.0
    - python >=3.7.8,<4.0
  run:
    - emoji >=2.0.0,<3.0.0
    - python >=3.7.8,<4.0
    - python-yakh <0.4.0,>=0.3.0
    - rich >=12.2.0,<13.0.0

test:
  imports:
    - beaupy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/petereon/beaupy
  doc_url: https://petereon.github.io/beaupy/
  summary: A library of elements for interactive TUIs in Python
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - petereon
    - thewchan
