{% set name = "beaupy" %}
{% set version = "3.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/beaupy-{{ version }}.tar.gz
  sha256: 746c83d859ed4efb4c2a4199c185e5686f76f7cde494e6d4d65e01d59a2ade30

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.2.0
    - python >=3.7.8,<3.12
  run:
    - python >=3.7.8,<3.12
    - rich >=12.2.0
    - emoji >=2.0.0,<3.0.0
    - python-yakh ==0.3.2
    - questo >=0.2.2,<0.3.0

test:
  imports:
    - beaupy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/petereon/beaupy
  doc_url: https://petereon.github.io/beaupy/
  summary: A library of elements for interactive TUIs in Python
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - petereon
    - thewchan
