{% set name = "beaupy" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/beaupy-{{ version }}.tar.gz
  sha256: a7933312bd11f394bf9a7f508f2b635622d216019f511839af97c9f33e6fe5da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - click >=8.1.3,<9.0.0
    - emoji >=2.0.0,<3.0.0
    - python >=3.6,<4.0
    - rich >=12.2.0,<13.0.0

test:
  imports:
    - beaupy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/petereon/beaupy
  doc_url: https://petereon.github.io/beaupy/
  summary: A library of elements for interactive TUIs in Python
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
