{% set name = "beaupy" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/beaupy-{{ version }}.tar.gz
  sha256: 07aae1772811ebe51065e0d0e5d90940a690b0d124f73d01662a49a71138bd98

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7.8,<4.0.0
  run:
    - pyproject-flake8 ==0.0.1a4
    - python >=3.7.8,<4.0.0
    - readchar >=4.0.0,<5.0.0
    - rich >=12.2.0,<13.0.0
    - emoji >=2.0.0,<3.0.0

test:
  imports:
    - beaupy

about:
  home: https://github.com/petereon/beaupy
  doc_url: https://petereon.github.io/beaupy/
  summary: A library of elements for interactive TUIs in Python
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
